name: DEPLOY
on:
  push:
    branches:
    - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.2
      with:
        switches: -avzr --delete
        path: src/
        remote_path: /home/prysdbpplus/public_html/test/
        remote_host: 156.67.218.142
        remote_user: prysdbpplus
        remote_key: ${{ secrets.DEPLOY_KEY }}
